### ISSUE TITLE
bug: The navbar has "contacts" it should be "contact" or "contact us", changing it in every page

### ISSUE THREAD

**Issue by 1Shubham7** [NageshMandal/Engineering-Notes-Website#1050]
![isse](https://github.com/NageshMandal/Engineering-Notes-Website/assets/116020663/9c72f6cb-0d18-4920-afe4-9727bebc9871)

The navbar text should be changed .

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by sanyamk0** [comment]
The size of the message box (textarea) is not set horizontally, and if we pull it, it expands and looks terrible. Additionally, the location of the theme icon across the entire website is also incorrect.
Please assign this issue to me because I can solve this issue in a matter of minutes.
Additionally, I'd be glad to contribute more to this project.

The issue in the below image must be resolved as soon as possible.
![image](https://github.com/NageshMandal/Engineering-Notes-Website/assets/96984179/d4386bf2-83f0-483b-b8f7-1a24640b5682)
