### ISSUE TITLE
Add Projects Page with Relevant Projects [GSSOC'23]

### ISSUE THREAD

**Issue by vishnu9865** [NageshMandal/Engineering-Notes-Website#79]
## Existing
 - The Projects link in navbar does not point to anything.
## Proposal
 - Add a Projects page (UI).
 - Page will display sample projects.
 - Will include a form for students to submit their projects for display.

I would like to contribute to this project in this regard.
@NageshMandal Please assign this task to me.
Thanks in advance. 👍🏽😊

**Comment by premsaivarmachekuri** [comment]
@NageshMandal, I would like to bring your attention to the issue "Add Projects Page with Relevant Projects [GSSOC'23]" (#79) and express my interest in contributing to this task.

As per the existing issue, the Projects link in the navbar currently does not point to anything. To address this, I propose adding a Projects page to the UI. This page will serve as a showcase for sample projects and provide a form for students to submit their own projects for display.

I believe that implementing this feature will greatly enhance the user experience and provide a platform for students to showcase their work. I am enthusiastic about taking on this task and contributing to the project in this capacity.

I kindly request you to assign the issue #79 to me so that I can begin working on it. I am excited to be a part of GSSOC'23 and contribute to the growth and improvement of the project.

Thank you for your consideration and support.

Best regards,
Premsai Varma

**Comment by vishnu9865** [comment]
@NageshMandal Thank you for Assigning this Task to me. 👍🏽😊

**Comment by vishnu9865** [comment]
@NageshMandal Sir, I there is any change required in this PR above. Please feel free to ask me.
Thank you,
Regards,
Jeyavishnu @vishnu9865
